---
title: "condrift: Conditional drift in an admixture graph"
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

suppressPackageStartupMessages(library(ggplot2, quietly = TRUE))
```

```{r}
joint_drift_model <- function(mu, Sigma) {
  structure(list(mu = mu, Sigma = Sigma),
            class = "drift_model")
}

condition <- function(model, index, freq) {
  mu_1 <- model$mu[-index]
  mu_2 <- model$mu[index]
  Sigma_11 <- model$Sigma[-index, -index]
  Sigma_12 <- model$Sigma[-index, index]
  Sigma_21 <- model$Sigma[index, -index]
  Sigma_22 <- model$Sigma[index, index]
  
  X <- Sigma_12 %*% solve(Sigma_22)
  new_mu <- mu_1 + X %*% (freq - mu_2)
  new_Sigma <- Sigma_11 - X %*% Sigma_21
  
  joint_drift_model(new_mu, new_Sigma)
}

plot.drift_model <- function(x, ..., indices = c(1, 2)) {
  i <- indices[1]
  j <- indices[2]
  mu <- x$mu[c(i,j)]
  Sigma <- x$Sigma[c(i,j), c(i,j)]
  
  range1 <- range2 <- seq(0, 1, length.out = 200)
  data.grid <- expand.grid(f1 = range1, f2 = range2)
  q.samp <- cbind(data.grid, 
                  prob = mvtnorm::dmvnorm(data.grid, mean = mu, sigma = Sigma))

  ggplot(q.samp, aes(x = f1, y = f2, z = prob)) + 
    geom_contour() +
    coord_equal(xlim = c(0, 1), ylim = c(0, 1), ratio = 1)
}
```

```{r}
test_mu <- c(0.5, 0.2, 0.6)
test_Sigma <- matrix(c(
  0.1,  0.06, 0.1,
  0.06, 0.1,  0.0,
  0.1,  0.0,  0.3
  ), byrow = TRUE, nrow = 3)
model <- joint_drift_model(test_mu, test_Sigma)
plot(model) + xlab("Pop 1") + ylab("Pop 2")
plot(model, indices = c(1,3)) + xlab("Pop 1") + ylab("Pop 3")
plot(model, indices = c(2,3)) + xlab("Pop 2") + ylab("Pop 3")
```

```{r}
plot(condition(model, index = 1, freq = 0.1))
plot(condition(model, index = 1, freq = 0.4))
plot(condition(model, index = 1, freq = 0.6))
plot(condition(model, index = 1, freq = 0.8))
```

```{r}
expected_F4 <- function(model, a, b, c, d) {
  # E[(a-b)(c-d)] = E[ac]-E[ad]-E[bc]+E[bd]
  # E[xy] = E[x]E[y] + Cov(x,y)
  Eac <- model$mu[a] * model$mu[c] + model$Sigma[a, c]
  Ead <- model$mu[a] * model$mu[d] + model$Sigma[a, d]
  Ebc <- model$mu[b] * model$mu[c] + model$Sigma[b, c]
  Ebd <- model$mu[b] * model$mu[d] + model$Sigma[b, d]
  Eac - Ead - Ebc + Ebd
}

conditional_expected_F4 <- function(model, a, b, c, d, x) {
  function (f) {
    conditional_model <- condition(model, index = x, freq = f)
    expected_F4(conditional_model, a, b, c, d)  
  }
}


```

```{r}
test_mu <- c(0.5, 0.2, 0.6, 0.5, 0.5)
test_Sigma <- matrix(c(
  0.1,  0.06, 0.1, 0.04, 0.05,
  0.06, 0.1,  0.0, 0.00, 0.00,
  0.1,  0.0,  0.3
  ), byrow = TRUE, nrow = 3)
model <- joint_drift_model(test_mu, test_Sigma)
```
